table _Medidas
	lineageTag: c63fdbc5-3cee-4305-880b-e8bcabdbd6fb

	measure _Base = CALCULATE(DISTINCTCOUNT(vw_Respondente[CodRespondente]), All(vw_Resposta[Resposta]))
		formatString: 0
		lineageTag: b8067eb3-d32d-4ab3-bd02-710a08405798

	measure _Percentual =
			
			
			DIVIDE(DISTINCTCOUNT(vw_Resposta[CodRespondente]), CALCULATE([_Base]))  *100
		lineageTag: 16fcc0c5-84a6-4b34-a795-e0ebbd25c918

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Label1Lembranca = ```
			"Lembrança de Marca - " & SELECTEDVALUE(tbPeriodoMaster[Agrupamento de período])  
			```
		lineageTag: 1b83adca-c701-439a-a3fe-247ae5b6f0fd

	measure CorMarcaLembrada =
			if(SELECTEDVALUE(vw_Resposta[Resposta])="Coca","#FF0000",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Convencao","#009900",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Dolly","#669900",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Fanta","#FF8C10",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Guaraná","#006600",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Guaraná Kuat","#006600",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="H2O","#C6084",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Pepsi","#0000FF",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Refri","#008000",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Refri de Laranja","#DFB948",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="refri de Limão","#66FF66",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Schin","#009900",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Schweppes","#FFd966",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Soda","#66FF66",
			if (SELECTEDVALUE(vw_Resposta[Resposta]) in {"Tônica","Tonica"},"#2F75B5",
			if (SELECTEDVALUE(vw_Resposta[Resposta]) in {"Tubaína","Tubaina"},"#A50021",
			if (SELECTEDVALUE(vw_Resposta[Resposta])="Tutti Frutti","","#8D8D8D"
			)))))))))))))))))
		lineageTag: 614b01e6-7ad8-4876-8ae2-5d26b9954373

	measure CorMarcaFreq = ```
			if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Citrus","#8d8d8d",
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Coca","#FF0000" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Convencao","#CC0000", 
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Dolly","#669900" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Fanta","#7030A0" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Guaraná","#00B050", 
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Guaraná Kuat","#00B050", 
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "H2O","#C6E0B4" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Natural","#548235", 
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Outra","#8d8d8d" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Pepsi","#0000FF" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Refri","#0066FF" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Refri de Laranja","#8d8d8d" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Refri de Limão","#8d8d8d" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Refri MG","#8d8d8d" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Schin","#009900" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Schweppes","#8d8d8d" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Soda","#66FF66" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Tônica","#2F75B5" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Tubaína","#A50021" ,
				if(SELECTEDVALUE(vw_Resposta[nomemarca])= "Tutti Fruti","#008000" , "#8d8d8d" )))))))))))))))))))))
			```
		lineageTag: efed319f-9de2-43cb-a8d8-5b6ce3650c1c

	measure _TesteT = ```
			
			var PercentualAnt = CALCULATE([_Percentual], FILTER(ALLSELECTED(tbPeriodoMaster), tbPeriodoMaster[SequenciaMes]=MAX(tbPeriodoMensal[SequenciaMes])-1))
			
			var PercentualAtual = CALCULATE([_Percentual], FILTER(ALLSELECTED(tbPeriodoMaster), tbPeriodoMaster[SequenciaMes]=MAX(tbPeriodoMensal[SequenciaMes])))
			
			var BaseAnt = CALCULATE([_Base], FILTER(ALLSELECTED(tbPeriodoMaster), tbPeriodoMaster[SequenciaMes]=MAX(tbPeriodoMensal[SequenciaMes])-1))
			
			var BaseAtual = CALCULATE([_Base], FILTER(ALLSELECTED(tbPeriodoMaster), tbPeriodoMaster[SequenciaMes]=MAX(tbPeriodoMensal[SequenciaMes])))
			
			VAR T = IF(OR(ISBLANK(PercentualAnt),ISBLANK(PercentualAtual)), BLANK(), ((PercentualAnt - PercentualAtual) / SQRT(ABS(((PercentualAnt * (100 - PercentualAnt)) / baseAnt) + ((PercentualAtual * (100 - PercentualAtual)) / baseAtual)))))
			RETURN
			T
			
			
			```
		formatString: 0
		lineageTag: 3ea668fc-bf35-479d-b23a-55158cc4eb86

	measure '_Teste T2' = ```
			
			 
			Var PercentualAnt = CALCULATE([_Percentual], FILTER(ALLSELECTED(tbPeriodoMaster), tbPeriodoMaster[SequenciaMes]= MAX( tbPeriodoMaster[SequenciaMes]) - 1))
			var PercentualAtual = CALCULATE([_Percentual], FILTER(ALLSELECTED(tbPeriodoMaster),  tbPeriodoMaster[SequenciaMes]= MAX( tbPeriodoMaster[SequenciaMes])))
			Var baseAnt = CALCULATE([_Base], FILTER(ALLSELECTED(tbPeriodoMaster),  tbPeriodoMaster[SequenciaMes] = MAX( tbPeriodoMaster[SequenciaMes]) - 1))
			var baseAtual = CALCULATE([_Base], FILTER(ALLSELECTED(tbPeriodoMaster),  tbPeriodoMaster[SequenciaMes]= MAX( tbPeriodoMaster[SequenciaMes]) ))
			VAR T = IF(OR(ISBLANK(PercentualAnt),ISBLANK(PercentualAtual)), BLANK(), ((PercentualAnt - PercentualAtual) / SQRT(ABS(((PercentualAnt * (100 - PercentualAnt)) / baseAnt) + ((PercentualAtual * (100 - PercentualAtual)) / baseAtual)))))
			RETURN
			T
			```
		lineageTag: 566e4319-f80f-4221-8a6c-91b1d719a537

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _TituloComentarios = "Comentários Gerais"
		lineageTag: e87a5859-b2fb-42f5-83f0-e6550362bb41

	measure 'Quantidade de Comentários' = CALCULATE(DISTINCTCOUNT(tbComentarios[CodRespondente]))
		formatString: 0
		lineageTag: 6da78fd6-0e7c-420c-ba62-6c0d5cd8aa81

	measure _Quantidade = DISTINCTCOUNT(vw_Resposta[CodRespondente])
		formatString: 0
		lineageTag: f41645bf-01ae-41aa-921f-942cd1d0603e

	measure _BasePergunta = CALCULATE(DISTINCTCOUNT(vw_Resposta[CodRespondente]), ALLEXCEPT(vw_Resposta, vw_Resposta[Resposta]))
		formatString: 0
		lineageTag: 65a35e99-b8ce-4085-b365-cfd18d25f24f

	measure _PercentualPergunta = ```
			DIVIDE([_Quantidade],[_BasePergunta]) * 100 
			```
		lineageTag: 7b1b6be6-9c37-4785-839b-b04311632f6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _BasePergunta2 = CALCULATE(DISTINCTCOUNT(vw_Resposta[CodRespondente]), ALLSELECTED(vw_Resposta[Resposta]))
		formatString: 0
		lineageTag: 439134e1-c98b-4972-8a6a-3389993f484e

	measure _PercentualAtributoValor = ```
			DIVIDE([_Quantidade], [_BasePergunta2]) * 100 
			```
		lineageTag: 2dbba69e-7874-4d93-82e7-f5b717845bcb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: 3ceb1bba-fbc5-42d5-918e-31297982f841
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

