table vw_Resposta
	lineageTag: 6421991d-897c-457a-a3c3-95fa613a1c12

	measure _Base = CALCULATE(DISTINCTCOUNT(vw_Respondente[CodRespondente]), all(vw_Resposta[Resposta]))
		formatString: 0
		lineageTag: b8067eb3-d32d-4ab3-bd02-710a08405798

	measure _Percentual =
			
			
			DIVIDE(DISTINCTCOUNT(vw_Resposta[CodRespondente]), CALCULATE([_Base]))  *100
		lineageTag: 16fcc0c5-84a6-4b34-a795-e0ebbd25c918

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CodQuestao
		dataType: int64
		formatString: 0
		lineageTag: 3c691d92-409e-4cc3-a1d9-2563af4af3e4
		summarizeBy: none
		sourceColumn: CodQuestao

		annotation SummarizationSetBy = Automatic

	column CodRespondente
		dataType: int64
		formatString: 0
		lineageTag: 1efb4c47-3772-4e08-a428-19c8692b045b
		summarizeBy: none
		sourceColumn: CodRespondente

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: string
		lineageTag: 6fc3a19c-91d3-462c-8470-d9ddf23213d0
		summarizeBy: none
		sourceColumn: Resposta

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: 72a66560-e524-40fe-9886-1f0ee56654fd
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column NomeMarca
		dataType: string
		lineageTag: cb8d2d19-3c6c-4e6f-a3fa-fd6c051d4cfe
		summarizeBy: none
		sourceColumn: NomeMarca

		annotation SummarizationSetBy = Automatic

	partition vw_Resposta = m
		mode: import
		source =
				let
				    Source = Sql.Database("RICHARD_WIN\SQLEXPRESS", "REFRI"),
				    dbo_vw_Resposta = Source{[Schema="dbo",Item="vw_Resposta"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_vw_Resposta,{"Controle"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

